"""Wholesale replacement content for articles rewritten after publication.

Applied by `_apply_content_migrations` in database.py. Kept out of that file
because a 15KB HTML string buried in a migration is unreadable, and out of the
blog_seed modules because those only ever INSERT new slugs — these overwrite
articles that already exist in production.

Each entry is a full replacement body. Setting the whole field is deliberate:
chaining six REPLACE() calls against live HTML is how a migration half-applies
and leaves an article in a state nobody designed.
"""

# ── SEBI PIT: three articles merged into one ────────────────────────────────
#
# The site had four PIT articles. Crawling production showed the pillar sharing
# ~40% of its distinctive vocabulary with two of them, because the pillar
# carried a "What is UPSI" section and a "What's the penalty?" section that were
# the entire subject of those two spokes. Google had to choose between them, and
# the pillar was likely to win on every query the spokes were written for.
#
# Merged in: what-is-upsi-regulation-2-1-n, insider-trading-penalties-case-studies.
# Left standing: sebi-pit-compliance-solutions-founders-kmp — an operational
# build-guide for a different reader, which never flagged against the pillar.
PIT_MERGED_TITLE = (
    "SEBI Insider Trading Rules (PIT), Explained: UPSI, the Trading Window, "
    "Penalties and the Landmark Cases"
)

PIT_MERGED_SUMMARY = (
    "What counts as UPSI after the 2025 expansion, when the trading window shuts, "
    "who ends up in default, and the penalties that reach three times the profit."
)

PIT_MERGED_CONTENT = (
    "<p>A senior executive knows the quarterly numbers will beat the market's expectations. "
    "Results go public on Friday; on Wednesday she buys shares, telling herself she'd have "
    "bought anyway. That intent doesn't matter. She traded while holding unpublished "
    "price-sensitive information, and under the PIT Regulations the penalty can reach the "
    "higher of ₹25 crore or three times her gain — before any criminal exposure.</p>"

    "<blockquote><p><strong>The bottom line</strong></p>"
    "<p>The PIT Regulations ban trading in a listed company's securities while you possess "
    "<strong>unpublished price-sensitive information (UPSI)</strong>, and ban passing that "
    "information to others except for a legitimate purpose.</p>"
    "<p>A <strong>2025 amendment (effective 10 June 2025)</strong> widened UPSI to roughly "
    "<strong>16 categories</strong> aligned with LODR's material events; companies must log "
    "UPSI in a <strong>structured digital database</strong> and close the "
    "<strong>trading window</strong> when insiders may hold it.</p>"
    "<p>Penalties run to the <strong>higher of ₹25 crore or three times the profit</strong>, "
    "plus imprisonment of up to <strong>10 years</strong>.</p></blockquote>"

    "<h2>What do the PIT Regulations actually prohibit?</h2>"
    "<p>The <strong>SEBI (Prohibition of Insider Trading) Regulations, 2015</strong> — in "
    "force since <strong>15 May 2015</strong> — do two core things.</p>"
    "<p>First, <strong>Regulation 4</strong> bars an insider from trading in securities when in "
    "possession of UPSI. Note the word: <em>possession</em>, not use. You do not have to act "
    "<em>because</em> of the information for the prohibition to bite.</p>"
    "<p>Second, <strong>Regulation 3</strong> bars communicating UPSI to anyone, or procuring it "
    "from anyone, except where it is needed for a <strong>legitimate purpose</strong>, to "
    "perform duties, or to discharge a legal obligation. The person who passes the information "
    "is liable even if they never trade a single share.</p>"

    "<h2>What is UPSI? The two limbs</h2>"
    "<p><em>Governs this section: Regulation 2(1)(n), PIT Regulations, 2015</em></p>"
    "<p>Information is UPSI only when <strong>both</strong> limbs are satisfied:</p>"
    "<ol>"
    "<li><strong>Unpublished</strong> — not \"generally available\", meaning not accessible "
    "to the public on a non-discriminatory basis. Dissemination through the stock exchanges is "
    "the gold standard of generally available.</li>"
    "<li><strong>Price sensitive</strong> — likely to <em>materially</em> affect the price "
    "of the securities once it does become generally available.</li>"
    "</ol>"
    "<p>Two things follow that people get wrong. A rumour circulating widely on social media is "
    "not \"generally available\" merely because it is circulating. And information is price "
    "sensitive in <em>either</em> direction — bad news is UPSI exactly as much as good news.</p>"

    "<h2>The expanded UPSI list after 10 June 2025</h2>"
    "<p><em>Governs this section: Regulation 2(1)(n) as amended by the SEBI (PIT) (Amendment) "
    "Regulations, 2025</em></p>"
    "<p>For years the definition leaned on five illustrative categories — financial results, "
    "dividends, capital-structure changes, mergers and changes in key personnel — and "
    "companies treated anything outside them as fair game. SEBI closed that gap by aligning UPSI "
    "with Regulation 30 and Schedule III of the LODR Regulations, taking the list to roughly "
    "<strong>16 categories</strong>. Among the additions:</p>"
    "<ul>"
    "<li><strong>decisions on proposed fund raising</strong>;</li>"
    "<li><strong>agreements which may impact the management or control</strong> of the company;</li>"
    "<li><strong>initiation of a forensic audit</strong> for financial misstatement, siphoning or "
    "diversion of funds, and <strong>receipt of the final report</strong>;</li>"
    "<li><strong>fraud or defaults</strong> by the company, its promoters, directors, KMP or "
    "subsidiary, and <strong>arrests</strong> of key persons;</li>"
    "<li><strong>changes in rating(s)</strong>, other than ESG ratings;</li>"
    "<li><strong>resolution plans and restructuring</strong> of loans or borrowings;</li>"
    "<li><strong>one-time settlements</strong> with banks, and admission into insolvency "
    "proceedings;</li>"
    "<li><strong>grant, withdrawal, surrender, cancellation or suspension of key licences or "
    "regulatory approvals</strong>;</li>"
    "<li><strong>guarantees, indemnities or surety</strong> given for third parties outside the "
    "normal course of business;</li>"
    "<li><strong>material litigation or disputes</strong>, and awards or orders of regulators, "
    "courts or tribunals.</li>"
    "</ul>"
    "<p>The amendment came with two flexibilities. UPSI that <strong>originates outside</strong> "
    "the company can be entered in the database within <strong>2 calendar days</strong> of "
    "receipt, and the trading window need not close for such externally-sourced UPSI where "
    "designated persons are unlikely to hold it.</p>"

    "<h2>When does UPSI stop being UPSI?</h2>"
    "<p><em>Governs this section: Regulation 2(1)(e) — \"generally available information\"</em></p>"
    "<p>UPSI dies the moment the information becomes generally available, which in practice means "
    "dissemination through the stock exchanges. This is why trading windows reopen only "
    "<strong>48 hours after</strong> results are declared — the market needs time to absorb "
    "the disclosure.</p>"
    "<p>Selective disclosure does not help. Telling one analyst, one fund or one journalist does "
    "not make information generally available; it simply multiplies the number of insiders.</p>"

    "<h2>Who is an \"insider\" and a \"connected person\"?</h2>"
    "<p>An <strong>insider</strong> is anyone who is a connected person, or who is in possession "
    "of or has access to UPSI. Possession alone is enough — you do not need a job title.</p>"
    "<p>A <strong>connected person</strong> is anyone associated with the company in the six "
    "months before the act, in a position giving access to UPSI. That reaches directors, "
    "employees, bankers, auditors, lawyers and consultants.</p>"
    "<p><strong>Immediate relatives</strong> of connected persons are presumed to be connected. "
    "The presumption reverses the burden of proof: it is for them to show they had no access, "
    "not for SEBI to show they did.</p>"

    "<h2>What is the trading window, and when does it close?</h2>"
    "<p>The trading window is the period in which designated persons may deal in the company's "
    "securities. It <strong>closes</strong> when UPSI is likely to exist — most obviously "
    "from the end of a quarter until 48 hours after results are published.</p>"
    "<p>While it is shut, designated persons cannot trade even with pre-clearance. When it is "
    "open, trades above the prescribed value still need <strong>pre-clearance</strong> from the "
    "compliance officer, and a <strong>contra-trade</strong> within six months of an earlier "
    "trade is barred.</p>"

    "<h2>The structured digital database</h2>"
    "<p><em>Governs this section: Regulations 3(5) and 3(6), PIT Regulations, 2015</em></p>"
    "<p>Every listed company must maintain a <strong>structured digital database (SDD)</strong> "
    "recording the nature of each item of UPSI along with the names and PANs of everyone who "
    "shared it and everyone who received it. Entries need time-stamped, non-tamperable audit "
    "trails, and must be preserved for at least <strong>eight years</strong>.</p>"
    "<p>UPSI originating outside the company — a regulator's communication, an acquirer's "
    "approach — must reach the SDD within <strong>2 calendar days</strong> of receipt.</p>"
    "<blockquote><p><strong>Practitioner's note</strong></p>"
    "<p>The SDD is SEBI's first stop in every insider trading investigation. If someone traded "
    "profitably and the SDD shows they were in on the UPSI, the case is largely built. If the SDD "
    "is incomplete, the company itself faces action for the lapse. Keep it contemporaneous — "
    "retro-fitted entries show up in the audit trail and are worse than no entry at all.</p>"
    "</blockquote>"

    "<h2>What is a trading plan, and what changed in 2024?</h2>"
    "<p>A <strong>trading plan</strong> under Regulation 5 lets someone who is permanently in "
    "possession of UPSI — a CFO, say — trade lawfully by committing to trades well in "
    "advance, then losing all discretion over them.</p>"
    "<p>SEBI eased the mechanics in 2024: the cool-off period between submitting a plan and its "
    "first trade came down from six months to <strong>120 days</strong>, and the minimum plan "
    "duration from twelve months to <strong>two consecutive quarters</strong>. The plan must be "
    "approved by the compliance officer and disclosed to the exchanges, and once approved it is "
    "irrevocable.</p>"

    "<h2>The penalty architecture</h2>"
    "<p><em>Governs this section: Sections 11, 11B, 11(4), 15G, 15HB and 24, SEBI Act, 1992</em></p>"
    "<ul>"
    "<li><strong>Adjudication (s.15G):</strong> trading on UPSI, communicating it, or procuring it "
    "each attract a penalty of <strong>not less than ₹10 lakh, up to ₹25 crore or three "
    "times the profit made, whichever is higher</strong>. Related lapses such as disclosure "
    "defaults and code violations fall under separate sections including 15A and 15HB.</li>"
    "<li><strong>Directions (ss.11, 11B, 11(4)):</strong> SEBI can restrain a person from the "
    "securities market, suspend them from holding office in listed companies, freeze alleged "
    "gains through interim orders often passed without hearing them first, and order "
    "<strong>disgorgement</strong> — handing back profits with interest, credited to the "
    "Investor Protection and Education Fund.</li>"
    "<li><strong>Prosecution (s.24):</strong> imprisonment up to <strong>10 years</strong> or a "
    "fine up to <strong>₹25 crore</strong>, or both. Section 24 prosecutions are rare but "
    "real, and settlement is unavailable for serious, market-wide frauds.</li>"
    "<li><strong>Settlement:</strong> many PIT matters end through SEBI's settlement mechanism "
    "— settlement amounts, voluntary debarment and disgorgement, without admission of guilt.</li>"
    "</ul>"
    "<p>The three-times multiplier is the part insiders underestimate. On a large gain it dwarfs "
    "the ₹25 crore figure, and after-the-fact rationalisation is no defence once possession "
    "and trading coincide.</p>"

    "<h2>Who ends up \"in default\"?</h2>"
    "<p><em>Governs this section: Regulations 3, 4, 9 and 10, PIT Regulations, 2015</em></p>"
    "<ol>"
    "<li><strong>The trading insider</strong> — the person who dealt while in possession of "
    "UPSI (Reg 4).</li>"
    "<li><strong>The tipper</strong> — the insider who communicated UPSI outside a legitimate "
    "purpose (Reg 3(1)).</li>"
    "<li><strong>The tippee</strong> — the person who procured or induced communication of "
    "UPSI (Reg 3(2)) and traded.</li>"
    "<li><strong>Immediate relatives and connected persons</strong> — presumed to possess "
    "UPSI, with the burden of proof reversed onto them.</li>"
    "<li><strong>The listed company and its compliance officer</strong> — for Code of Conduct "
    "failures, missed exchange reporting and SDD gaps.</li>"
    "</ol>"

    "<h2>The landmark cases</h2>"
    "<p><strong>Hindustan Lever v SEBI (1998) — what \"unpublished\" means.</strong> HLL "
    "bought 8 lakh shares of Brooke Bond Lipton from UTI weeks before the HLL–BBLIL merger "
    "announcement. SEBI treated HLL as an insider trading on unpublished merger information. The "
    "appellate authority set the compensation direction aside, reasoning that the impending merger "
    "was already widely reported and so generally known. The case forced Indian law to sharpen "
    "what \"unpublished\" actually means.</p>"
    "<p><strong>Rakesh Agrawal v SEBI (SAT, 2004) — motive under the old regime.</strong> The "
    "managing director of ABS Industries bought shares through his brother-in-law ahead of Bayer's "
    "takeover, knowing the deal. SAT accepted he possessed UPSI but found he acted to help the "
    "acquisition succeed in the company's interest, which diluted the charge under the 1992 "
    "regulations. The 2015 regulations answered this case directly by making <em>possession</em>, "
    "not motive, the operative test.</p>"
    "<p><strong>SEBI v Abhijit Rajan (Supreme Court, 2022) — the direction of advantage.</strong> "
    "Gammon Infrastructure's managing director sold shares before the company announced termination "
    "of certain shareholder agreements. The Supreme Court held the terminated contracts were a "
    "small fraction of the order book, and that he had sold <em>against</em> his informational "
    "advantage rather than exploiting it. The judgment reintroduced a narrow profit-motive lens — "
    "but only where the trade runs contrary to what the information would suggest.</p>"
    "<p><strong>Balram Garg v SEBI (Supreme Court, 2022) — proximity is not proof.</strong> "
    "The Court held that a family relationship alone does not establish that UPSI was communicated. "
    "Cogent evidence of actual communication is needed, though trading patterns plus proximity can "
    "still build a circumstantial case.</p>"

    "<h2>Disclosure obligations</h2>"
    "<p><em>Governs this section: Regulations 6 and 7, PIT Regulations, 2015</em></p>"
    "<ul>"
    "<li><strong>Initial disclosure:</strong> every promoter, member of the promoter group, KMP "
    "and director discloses their holdings within 7 days of appointment or of becoming a promoter.</li>"
    "<li><strong>Continual disclosure (Reg 7(2)):</strong> promoters, promoter group, designated "
    "persons and directors must disclose to the company within <strong>2 trading days</strong> "
    "every trade, or series of trades in a calendar quarter, whose value exceeds "
    "<strong>₹10 lakh</strong>. The company passes it to the exchanges within 2 trading days "
    "of receipt.</li>"
    "</ul>"

    "<h2>Worked example</h2>"
    "<p>A designated person learns of an unannounced large order win — UPSI under the expanded "
    "2025 list — buys shares for ₹40 lakh, and sells after the announcement for "
    "₹70 lakh. A ₹30 lakh profit.</p>"
    "<p>Under Section 15G the adjudicating officer may impose up to ₹25 crore, or three times "
    "₹30 lakh, whichever is higher — so up to ₹25 crore, with ₹10 lakh as the "
    "floor. In parallel an 11B direction can disgorge the ₹30 lakh with interest and debar him "
    "from the market for years, and the company must report the code violation to the exchanges. "
    "If SEBI prosecutes under Section 24, imprisonment up to 10 years is on the table.</p>"
    "<p>The ₹30 lakh gain carries a worst case several orders of magnitude larger.</p>"

    "<h2>Common mistakes</h2>"
    "<ol>"
    "<li><strong>Testing only the old five categories.</strong> The list is now roughly 16 — "
    "fund-raising decisions, forensic audits, licence actions and control-impacting agreements are "
    "expressly in.</li>"
    "<li><strong>Treating rumours as generally available.</strong> Only non-discriminatory public "
    "dissemination kills UPSI.</li>"
    "<li><strong>Believing motive is a defence.</strong> Possession while trading suffices. "
    "<em>Abhijit Rajan</em> helps only where the trade runs against the insider's informational "
    "advantage.</li>"
    "<li><strong>Tipping \"harmlessly\".</strong> The communicator is liable under Regulation 3 "
    "even if they never trade.</li>"
    "<li><strong>Forgetting external UPSI.</strong> Information received from outside must reach "
    "the SDD within 2 calendar days.</li>"
    "<li><strong>Reopening the window at announcement.</strong> It reopens 48 hours <em>after</em> "
    "the information becomes generally available.</li>"
    "<li><strong>Assuming small trades escape notice.</strong> Surveillance flags pre-announcement "
    "trades of all sizes; ₹10 lakh is a disclosure threshold, not an enforcement floor.</li>"
    "<li><strong>Ignoring interim orders.</strong> Gains can be frozen and you can be barred from "
    "the market without being heard first, years before the case is finally decided.</li>"
    "</ol>"

    "<h2>Compliance checklist</h2>"
    "<ol>"
    "<li>Map all UPSI categories into the Code of Fair Disclosure and the internal materiality "
    "policy.</li>"
    "<li>Log every UPSI event in the SDD contemporaneously, with external UPSI inside 2 calendar "
    "days.</li>"
    "<li>Close the trading window on UPSI crystallisation; reopen 48 hours after dissemination.</li>"
    "<li>Restrict UPSI sharing to need-to-know recipients and capture every recipient's name and "
    "PAN.</li>"
    "<li>Run pre-clearance for trades above the threshold and block contra-trades inside six "
    "months.</li>"
    "<li>File initial and continual disclosures on time, and report code violations to the "
    "exchanges.</li>"
    "<li>Preserve SDD entries, pre-clearance records and window-closure notices for at least eight "
    "years.</li>"
    "<li>Train designated persons that forwarding results on WhatsApp <em>is</em> communication of "
    "UPSI.</li>"
    "</ol>"

    "<h2>FAQ</h2>"
    "<p><strong>What is UPSI in simple terms?</strong> Information about a company or its "
    "securities that is not yet public and that would likely move the price materially once it "
    "is. Both limbs must be met.</p>"
    "<p><strong>What is the minimum penalty for insider trading?</strong> ₹10 lakh under "
    "Section 15G. The ceiling is ₹25 crore or three times the profit made, whichever is "
    "higher.</p>"
    "<p><strong>Can insider trading lead to jail in India?</strong> Yes. Section 24 of the SEBI Act "
    "provides imprisonment up to 10 years, a fine up to ₹25 crore, or both.</p>"
    "<p><strong>Is profit necessary for liability?</strong> No. Trading while in possession of UPSI "
    "is the contravention. Profit only scales the penalty and the disgorgement.</p>"
    "<p><strong>Do I have to have used the information?</strong> No. Regulation 4 turns on "
    "possession, not use.</p>"
    "<p><strong>When did the expanded UPSI list take effect?</strong> 10 June 2025, ninety days "
    "from the March 2025 notification.</p>"
    "<p><strong>Are ESG rating changes UPSI?</strong> The 2025 amendment covers changes in ratings "
    "<em>other than</em> ESG ratings.</p>"
    "<p><strong>How long must the SDD be preserved?</strong> At least eight years, with "
    "time-stamped, non-tamperable audit trails, and longer where proceedings are pending.</p>"
    "<p><strong>Does a family relationship prove UPSI was shared?</strong> Not by itself. "
    "<em>Balram Garg</em> requires cogent evidence of actual communication.</p>"
    "<p><strong>Can a case be settled?</strong> Many PIT proceedings conclude under SEBI's "
    "settlement regulations with monetary terms and voluntary restraints, subject to SEBI's "
    "discretion.</p>"

    "<h2>Primary sources</h2>"
    "<ul>"
    "<li>Regulations 2(1)(e), 2(1)(n), 3, 4, 5, 6, 7, 9 and 10, SEBI (Prohibition of Insider "
    "Trading) Regulations, 2015</li>"
    "<li>SEBI (Prohibition of Insider Trading) (Amendment) Regulations, 2025 — notification "
    "dated 11 March 2025, effective 10 June 2025</li>"
    "<li>Sections 11, 11B, 11(4), 12A, 15G, 15HB and 24, SEBI Act, 1992</li>"
    "<li>Regulation 30 and Schedule III, SEBI (LODR) Regulations, 2015</li>"
    "<li>Hindustan Lever Ltd. v SEBI (1998); Rakesh Agrawal v SEBI (SAT, 2004); SEBI v Abhijit "
    "Rajan (SC, 2022); Balram Garg v SEBI (SC, 2022)</li>"
    "</ul>"
)


# ── DPDP: the guide's timeline section defers to the dedicated article ──────
#
# The compliance-timeline section of dpdp-act-compliance-guide and the whole of
# dpdp-rules-2025-compliance-timeline covered identical ground with identical
# dates — the highest overlap on the site at 43%. The guide keeps a short
# orientation and hands the detail to the article built for it.
DPDP_TIMELINE_OLD_MARKER = "<h2>The compliance timeline: three phases</h2>"

DPDP_TIMELINE_NEW = (
    "<h2>The compliance timeline</h2>"
    "<p>The Rules were notified on <strong>13 November 2025</strong> and commence in three stages. "
    "In short: the Data Protection Board and the penalty framework are already live; "
    "<strong>Consent Manager registration opens 13 November 2026</strong>; and the obligations "
    "that take real work — notice, security safeguards, breach notification, retention limits, "
    "children's data and data principal rights — bite on <strong>13 May 2027</strong>.</p>"
    "<p>That last date is the one to plan against, and it is closer than it looks: the data "
    "inventory alone takes most organisations several months. Our "
    "<a href=\"/article/dpdp-rules-2025-compliance-timeline\">guide to the DPDP Rules commencement "
    "timeline</a> sets out which rule numbers land in which phase and what to build before each.</p>"
)
