"""One-off generator: converts the 20 Downloads/files markdown blogs into
blog_seed.py (BLOG_ARTICLES) in the exact article format the site uses
(HTML: <h2>/<h3>/<p>/<ul>/<ol>/<li>/<strong>/<em>/<blockquote>).
Run from the project root:  python3 scripts_gen_blogs.py
"""
import os
import re
import html

SRC = "/Users/piyush_kundnani/Downloads/files"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "blog_seed.py")

# filename -> (category_code, relevant Act)
META = {
    "01-RTI-Act.md":                 ("consumer", "RTI Act, 2005"),
    "02-RTE-Act.md":                 ("acts",     "RTE Act, 2009"),
    "03-Consumer-Protection-Act.md": ("consumer", "Consumer Protection Act, 2019"),
    "04-Fundamental-Rights.md":      ("acts",     "Constitution of India"),
    "05-Cyber-Crime-Laws.md":        ("acts",     "IT Act, 2000 & BNS, 2023"),
    "06-Online-Fraud-Remedies.md":   ("consumer", "IT Act, 2000"),
    "07-Rights-of-Women.md":         ("acts",     "Indian Law"),
    "08-What-is-GST.md":             ("acts",     "GST Act, 2017"),
    "09-GST-Registration.md":        ("corp",     "GST Act, 2017"),
    "10-LLP-Registration.md":        ("corp",     "LLP Act, 2008"),
    "11-Company-Registration.md":    ("corp",     "Companies Act, 2013"),
    "12-Startup-India-Registration.md": ("corp",  "Startup India Scheme"),
    "13-Udyam-Registration.md":      ("corp",     "MSME Act, 2006"),
    "14-Dematerialization-of-Shares.md": ("corp", "Companies Act, 2013"),
    "15-Trademark-Registration.md":  ("corp",     "Trade Marks Act, 1999"),
    "16-IPR-Explained.md":           ("acts",     "Intellectual Property Laws"),
    "17-Annual-Compliance-LLPs.md":  ("corp",     "LLP Act, 2008"),
    "18-Annual-Compliance-Companies.md": ("corp", "Companies Act, 2013"),
    "19-Director-Duties.md":         ("corp",     "Companies Act, 2013"),
    "20-Corporate-Governance.md":    ("corp",     "Companies Act, 2013"),
}


def inline(text):
    """Markdown inline -> HTML, escaping any literal & < > first."""
    text = html.escape(text, quote=False)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)      # bold
    text = re.sub(r"(?<!\w)\*(?!\s)(.+?)(?<!\s)\*(?!\w)", r"<em>\1</em>", text)  # italic
    return text.strip()


def slug_from(fname):
    base = re.sub(r"^\d+-", "", fname[:-3])      # drop "NN-" and ".md"
    return base.lower()


def to_html_and_summary(body_lines):
    """Convert markdown body (title/read-time already stripped) into the
    site's HTML and derive a summary from the Introduction paragraph."""
    # group into blocks separated by blank lines
    blocks, cur = [], []
    for ln in body_lines:
        if ln.strip() == "":
            if cur:
                blocks.append(cur); cur = []
        else:
            cur.append(ln.rstrip("\n"))
    if cur:
        blocks.append(cur)

    parts = []
    intro_text = None
    pending_heading = None  # tracks the last H2 to find Introduction body

    for blk in blocks:
        first = blk[0].strip()
        if first.startswith("## "):
            pending_heading = inline(first[3:].strip()).lower()
            parts.append("<h2>%s</h2>" % inline(first[3:].strip()))
        elif first.startswith("### "):
            parts.append("<h3>%s</h3>" % inline(first[4:].strip()))
        elif all(re.match(r"^\s*[-*]\s+", l) for l in blk):
            items = "".join("<li>%s</li>" % inline(re.sub(r"^\s*[-*]\s+", "", l)) for l in blk)
            parts.append("<ul>%s</ul>" % items)
        elif all(re.match(r"^\s*\d+\.\s+", l) for l in blk):
            items = "".join("<li>%s</li>" % inline(re.sub(r"^\s*\d+\.\s+", "", l)) for l in blk)
            parts.append("<ol>%s</ol>" % items)
        elif all(l.lstrip().startswith(">") for l in blk):
            txt = " ".join(re.sub(r"^\s*>\s?", "", l) for l in blk)
            parts.append("<blockquote>%s</blockquote>" % inline(txt))
        else:
            txt = " ".join(l.strip() for l in blk)
            parts.append("<p>%s</p>" % inline(txt))
            # capture first paragraph under "## Introduction" for the summary
            if intro_text is None and pending_heading == "introduction":
                intro_text = txt

    # summary: trim intro to ~1-2 sentences, <=200 chars
    base = intro_text or ""
    base = re.sub(r"[*_`]", "", base)            # strip md marks
    summary = ""
    for sent in re.split(r"(?<=[.!?])\s+", base):
        if len(summary) + len(sent) > 200 and summary:
            break
        summary = (summary + " " + sent).strip()
    summary = summary[:240].strip()
    return "".join(parts), summary


def main():
    out = ["# Auto-generated by scripts_gen_blogs.py — 20 blog articles.",
           "# Format matches seed_articles(): (title, slug, category, act, read_time, summary, content)",
           "BLOG_ARTICLES = ["]
    counts = {}
    for fname in sorted(META):
        cat, act = META[fname]
        with open(os.path.join(SRC, fname), encoding="utf-8") as f:
            lines = f.readlines()
        title, read_time, body = None, None, []
        for ln in lines:
            s = ln.strip()
            if title is None and s.startswith("# "):
                title = s[2:].strip(); continue
            m = re.match(r"\*Reading time:\s*~?\s*(\d+)\s*min", s, re.I)
            if m and read_time is None:
                read_time = "%s min read" % m.group(1); continue
            body.append(ln)
        content, summary = to_html_and_summary(body)
        slug = slug_from(fname)
        read_time = read_time or "8 min read"
        row = (title, slug, cat, act, read_time, summary, content)
        out.append("    %r," % (row,))
        counts[cat] = counts.get(cat, 0) + 1
        # sanity print
        print(f"{slug:32} cat={cat:9} act={act:28} rt={read_time:11} "
              f"sum={len(summary):3}c html={len(content):5}c")
    out.append("]")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print("\nPer-category:", counts, " total:", sum(counts.values()))
    print("Wrote", OUT)


if __name__ == "__main__":
    main()
